### ISSUE TITLE
ERROR: [youtube] YeCKTnJKG7s: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.`

### ISSUE THREAD

**Issue by skeeperloyaltie** [skeeperloyaltie/YT_playlist_downloader#8]
Anyone who can fix this ??

**Comment by skeeperloyaltie** [comment]
`[download] Downloading item 29 of 162
[youtube] Extracting URL: https://www.youtube.com/watch?v=YeCKTnJKG7s
[youtube] YeCKTnJKG7s: Downloading webpage
[youtube] YeCKTnJKG7s: Downloading ios player API JSON
[youtube] YeCKTnJKG7s: Downloading android player API JSON
ERROR: [youtube] YeCKTnJKG7s: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
Traceback (most recent call last):
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1702, in __extract_info
    ie_result = ie.extract(url)
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 715, in extract
    ie_result = self._real_extract(url)
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 4162, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1193, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: [youtube] YeCKTnJKG7s: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fr34k/Documents/music/YT_playlist_downloader/playlistDownloader/main.py", line 148, in <module>
    download_playlist(i, download_directory)
  File "/home/fr34k/Documents/music/YT_playlist_downloader/playlistDownloader/main.py", line 35, in download_playlist
    playlist = ydl.extract_info(playlist_url, download=True)
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1556, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1802, in process_ie_result
    return self.extract_info(
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1556, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1852, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1996, in __process_playlist
    entry_result = self.__process_iterable_entry(entry, download, collections.ChainMap({
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2028, in __process_iterable_entry
    return self.process_ie_result(
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1802, in process_ie_result
    return self.extract_info(
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1556, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1585, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1045, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/fr34k/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 984, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] YeCKTnJKG7s: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.`
